language: node_js
node_js:
        - "10"
before_script:
        - yarn
        - yarn add --dev coveralls

script:
        - yarn build

after_script:
        - jest --coverage --coverageReporters=text-lcov | coveralls
